apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificateexports.cert.trust.flolive.io
  labels:
    app.kubernetes.io/name: {{ include "cert-trust.name" . }}
    helm.sh/chart: {{ include "cert-trust.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: cert.trust.flolive.io
  scope: Namespaced
  names:
    kind: CertificateExport
    listKind: CertificateExportList
    plural: certificateexports
    singular: certificateexport
    shortNames:
      - cex
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretRef:
                  type: string
                schedule:
                  type: string
            status:
              type: object
              properties:
                lastSyncTime:
                  type: string
                  format: date-time
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Secret
          type: string
          jsonPath: .spec.secretRef
        - name: Schedule
          type: string
          jsonPath: .spec.schedule
