name: CI

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22"

            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Download dependencies
              run: go mod download

            - name: Verify dependencies
              run: go mod verify

            - name: Build
              run: go build ./cmd/cert-trust

            - name: Test
              run: go test ./...

    helm-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "v3.12.0"

            - name: Lint Helm chart
              run: |
                  helm lint charts/cert-trust

            - name: Package Helm chart
              run: |
                  helm package charts/cert-trust --destination ./dist

            - name: Test Helm template
              run: |
                  helm template cert-trust charts/cert-trust --dry-run

    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: cert-trust:test
                  platforms: linux/amd64
